### ISSUE TITLE
Identifier '__dirname' has already been declared

### ISSUE THREAD

**Issue by fangmuke** [atorber/puppet-bridge#3]
`__dirname` 是 Node.js 提供的一个全局变量，用来表示当前模块的目录名。

这个错误是由于在以下位置重复声明。

https://github.com/atorber/puppet-bridge/blob/de7e8e2d0715795601904f4a05fe1ca511c68ad4/src/agents/cixingguangming55555-wechat-bot.ts#L12

https://github.com/atorber/puppet-bridge/blob/de7e8e2d0715795601904f4a05fe1ca511c68ad4/src/agents/atorber-fused.ts#L18

https://github.com/atorber/puppet-bridge/blob/de7e8e2d0715795601904f4a05fe1ca511c68ad4/src/agents/ttttupup-wxhelper.ts#L25

https://github.com/atorber/puppet-bridge/blob/de7e8e2d0715795601904f4a05fe1ca511c68ad4/src/agents/jwping-wxbot.ts#L12

**Comment by atorber** [comment]
影响启动了吗？

**Comment by fangmuke** [comment]
> 影响启动了吗？

我在 electron 环境下，启动会报错。

**Comment by atorber** [comment]
新的npm包在electron还没试过，如果有问题，在之后的版本中修复

**Comment by atorber** [comment]
fixed
